### ISSUE TITLE
Wrong parameters set to parent Printer

### ISSUE THREAD

**Issue by pwinie** [sebastianfeldmann/phpbu-laravel#1]
there are given four parameters to contruct PrinterCli (from phpbu) in
https://github.com/sebastianfeldmann/phpbu-laravel/blob/master/src/Cmd/Printer.php#L33

but currently it accepts three:

https://github.com/sebastianfeldmann/phpbu/blob/master/src/Result/PrinterCli.php#L146

you should skip "null" as first parameter

**Comment by sebastianfeldmann** [comment]
I just released version 1.0.1 with a fix.
Thanks!
