### ISSUE TITLE
RuntimeException with message mysqldump - how can I specify the correct path?

### ISSUE THREAD

**Issue by howellkit3** [sebastianfeldmann/phpbu-laravel#3]
![phpbu](https://cloud.githubusercontent.com/assets/20956246/21558254/e043f338-ce71-11e6-848a-21048f5c45e7.png)
![phpbu-xml](https://cloud.githubusercontent.com/assets/20956246/21558255/e0473a16-ce71-11e6-9fee-4bb3e63344ec.png)

Giving my code, Im still unable to backup successfully.

This is my error
![phpbu-error](https://cloud.githubusercontent.com/assets/20956246/21558266/124a08a4-ce72-11e6-9871-57ca1e4d31e0.png)

How can I specify the correct path?

**Comment by sebastianfeldmann** [comment]
You can define a custom path to `mysqldump` using the `phpbu` xml or json configuration format
